# This file exists just to aid with local debugging
services:
    dummy_playwright:
        build:
            context: .
        environment:
            - PLAYWRIGHT_TEST_DIR=tests/Playwright
            - NETWORK_IFACE=eth0
            - DISPLAY=:1
            - VIRTUAL_HOST=$DDEV_HOSTNAME
            - HTTP_EXPOSE=8443:8444,9323:9324
            - HTTPS_EXPOSE=8444:8444,9324:9324
            - DDEV_UID=1000
            - DDEV_GID=1000
        command: tail -F anything
#        command: |
#            tail -F foo
#            printenv
#            sudo usermod -u ${DDEV_UID} pwuser
#            sudo groupmod -g ${DDEV_GID} pwuser
#            sudo chgrp -R ${DDEV_GID}  /etc/ssl/private
#            mkcert -install
#            vncserver -fg
